name: Build APK and AAB

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-android:
    name: ${{ matrix.build_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['14']
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
      - run: yarn --network-concurrency 1 --network-timeout 120000

      - name: Build Android Release APK
        run: |
          perl -pi -e 's/YOUR_SENTRY_TOKEN/$ENV{TOKEN}/' android/sentry.properties
          export SENTRY_PROPERTIES=android/sentry.properties
          cd android && ./gradlew assembleRelease
        env:
          TOKEN: ${{ secrets.SENTRY_TOKEN }}

      - name: Build Android Release AAB
        run: |
          export SENTRY_PROPERTIES=android/sentry.properties
          cd android && ./gradlew bundleRelease
        env:
          TOKEN: ${{ secrets.SENTRY_TOKEN }}

      - name: Upload AAB Release Asset
        if: github.event_name == 'release' && github.repository == 'turtlecoin/turtlecoin-mobile-wallet'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./android/app/build/outputs/bundle/release/app.aab
          asset_name: tonchan.aab
          asset_content_type: application/octet-stream

      - name: Upload APK Release Asset
        if: github.event_name == 'release' && github.repository == 'turtlecoin/turtlecoin-mobile-wallet'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./android/app/build/outputs/apk/release/app-release.apk
          asset_name: tonchan.apk
          asset_content_type: application/octet-stream
